name: orbital
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  http: ^1.2.1
  chat_bubbles: ^1.6.0
  email_validator: ^2.1.17
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  image_cropper: ^6.0.0
  flutter_spinkit: ^5.2.1
  auth_buttons: ^3.0.2
  google_sign_in: ^6.2.1
  flutter_chat_ui: ^1.6.14
  mockito: ^5.4.4
  build_runner: ^2.4.11
  build: ^2.4.1
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0
  add_2_calendar: ^3.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png
    - assets/logo.png
    - assets/loadingwallpaper.png
    
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"